import { Settings } from './types';

export const defaultSettings: Settings = {
  axis: null,
  easing: 'cubic-bezier(.03, .98, .52, .99)',
  exclude: null,
  gyroscope: true,
  gyroscopeMinAngleX: 45,
  gyroscopeMaxAngleX: 45,
  gyroscopeMinAngleY: 45,
  gyroscopeMaxAngleY: 45,
  gyroscopeSamples: 0,
  listener: window,
  max: 15,
  perspective: 1000,
  'parallax-children-shine': false,
  'parallax-children-disable': false,
  'parallax-children-invert': false,
  reset: true,
  reverse: false,
  scale: 1,
  shine: false,
  'max-shine': 45,
  'shine-opacity': 0,
  'shine-prerender': false,
  'shine-save': false,
  speed: 300,
  startX: 0,
  startY: 0,
};
